service: km

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    S3_BUCKET: km-expense-tracker-receipts
  httpApi: 
    cors: true

functions:
  trackerExpressApi:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /generate-presigned-url
          method: get
    timeout: 29

resources:
  Resources:
    LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        Policies:
          - PolicyName: S3UploadPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: 
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:*:*:*
                - Effect: Allow
                  Action: 
                    - s3:PutObject
                    - s3:GetObject
                    - s3:ListBucket
                    - s3:PutObjectAcl
                  Resource: 
                    - arn:aws:s3:::km-expense-tracker-receipts
                    - arn:aws:s3:::km-expense-tracker-receipts/uploads/*
